language: python
python:
  - 2.7
  - 3.4
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install -r test-requirements.txt
  - pip install -e .[tests]
script:
  - COVERAGE_PROCESS_START=`pwd`/.coveragerc trial spreadflow_observer_fs
  - coverage combine `pwd` `pwd`/_trial_temp
after_success:
  - coveralls
